### ISSUE TITLE
Improvement Request: Support maps in structs

### ISSUE THREAD

**Issue by equalsgibson** [kyberbits/forge#2]
At the minute, if you use a map in a golang struct and attempt to convert this using generate, it will fail (with the error along the lines of "cannot use NumField on map type"). 

I suggest that we allow map types by checking the type of the field, if it is map we convert it to a TS dictionary or Record: https://stackoverflow.com/questions/56353396/dictionary-type-in-typescript

with K being the index type in golang, and the value being the value. 

Example; map[string]any would be translated to:

```
interface MyInterface {
    data: Record<string, any>;
}
```

**Comment by equalsgibson** [comment]
I can work to implement this if this is an accepted idea

**Comment by aaronellington** [comment]
Yes this is acceptable and your contribution would be appreciated. :)
